world/apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import ProfileFollowView, ProfileView, RegisterView, SettingView

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(redirect_authenticated_user=True),
        name="register",
    ),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("settings/", SettingView.as_view(), name="settings"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/follow/<int:pk>/", ProfileFollowView.as_view(), name="follow"),
]

world/apps/articles/urls.py
from django.urls import path

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleFavoriteView,
    ArticleListView,
    ArticleUpdateView,
)

app_name = "articles"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("new/", ArticleCreateView.as_view(), name="create"),
    path(
        "article/<int:pk>/<slug:slug>/",
        ArticleDetailView.as_view(),
        name="detail",
    ),
    path(
        "article/edit/<int:pk>/",
        ArticleUpdateView.as_view(),
        name="edit",
    ),
    path(
        "article/delete/<int:pk>/",
        ArticleDeleteView.as_view(),
        name="delete",
    ),
    path(
        "article/favorite/<int:pk>/",
        ArticleFavoriteView.as_view(),
        name="favorite",
    ),
]

world/apps/comments/urls.py
from django.urls import path

from .views import CommentDeleteView

app_name = "comments"

urlpatterns = [path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete")]

world/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("world.apps.articles.urls")),
    path("", include("world.apps.accounts.urls")),
    path("comments/", include("world.apps.comments.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

world/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    # remove default fields
    username = None
    first_name = None
    last_name = None

    email = models.EmailField("Email address", unique=True)
    name = models.CharField(max_length=60)
    bio = models.TextField(blank=True)
    image = models.URLField(null=True, blank=True)

    following = models.ManyToManyField(
        "self", blank=True, related_name="followers", symmetrical=False
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile", args=[self.id])

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

world/apps/articles/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

import markdown
from taggit.managers import TaggableManager


class ArticleQuerySet(models.QuerySet):
    def with_favorites(self, user):
        return self.annotate(
            num_favorites=models.Count("favorites"),
            is_favorite=models.Exists(
                get_user_model().objects.filter(
                    pk=user.id, favorites=models.OuterRef("pk")
                ),
            )
            if user.is_authenticated
            else models.Value(False, output_field=models.BooleanField()),
        )


ArticleManager = models.Manager.from_queryset(ArticleQuerySet)


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    title = models.CharField(max_length=120)
    summary = models.TextField(blank=True)
    content = models.TextField(blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = TaggableManager(blank=True)

    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="favorites"
    )

    objects = ArticleManager()

    def __str__(self):
        return self.title

    @property
    def slug(self):
        return slugify(self.title)

    def get_absolute_url(self):
        return reverse(
            "articles:detail",
            kwargs={
                "pk": self.id,
                "slug": self.slug,
            },
        )

    def as_markdown(self):
        return markdown.markdown(self.content, safe_mode="escape", extensions=["extra"])

world/apps/comments/models.py
from django.conf import settings
from django.db import models

from world.apps.articles.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    content = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:50]

world/apps/accounts/forms.py
from django.contrib.auth import password_validation
from django.forms import CharField, ModelForm, PasswordInput

from .models import User


class UserCreationForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class SettingsForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        required=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name", "bio", "image"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

world/apps/articles/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "content", "tags"]
        widgets = {"summary": forms.TextInput()}

world/apps/comments/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

world/apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView

from world.apps.articles.models import Article

from .forms import SettingsForm, User, UserCreationForm


class ProfileView(ListView):
    context_object_name = "articles"
    template_name = "world/accounts/profile.html"

    def get_queryset(self):
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        articles = (
            Article.objects.select_related("author")
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if "favorites" in self.request.GET:
            return articles.filter(is_favorite=True)

        return articles.filter(author=profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        context["profile"] = profile
        context["is_following"] = profile.following.filter(
            pk=self.request.user.id
        ).exists()
        return context


class SettingView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = SettingsForm
    template_name = "world/accounts/settings.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)


class RegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "registration/register.html"
    redirect_authenticated_user = False

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a register page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid

    def get_success_url(self):
        return '/'


class ProfileFollowView(LoginRequiredMixin, UpdateView):
    fields = ["following"]
    http_method_names = ["post"]

    def get_queryset(self, **kwargs):
        return User.objects.filter(pk=self.kwargs["pk"]).exclude(
            pk=self.request.user.id
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.following.filter(id=request.user.id).exists():
            self.object.following.remove(request.user)
        else:
            self.object.following.add(request.user)

        return redirect(self.object.get_absolute_url())

world/apps/articles/views.py
from django.shortcuts import redirect
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from taggit.models import Tag

from world.apps.comments.forms import Comment, CommentForm
from world.apps.core.mixins import AuthorRequiredMixin, LoginRequiredMixin

from .forms import Article, ArticleForm


class ArticleListView(ListView):
    context_object_name = "articles"
    template_name = "world/articles/article_list.html"

    def get_queryset(self):
        queryset = (
            Article.objects.select_related("author")
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if tag := self.request.GET.get("tag"):
            return queryset.filter(tags__name__in=[tag])

        if self.request.user.is_authenticated and "own" in self.request.GET:
            return queryset.filter(author=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context


class ArticleDetailView(DetailView):
    context_object_name = "article"
    template_name = "world/articles/article_detail.html"

    def get_queryset(self):
        queryset = Article.objects.select_related("author").with_favorites(
            self.request.user
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        is_following = self.object.author.following.filter(
            pk=self.request.user.id
        ).exists()
        comments = (
            Comment.objects.filter(article=self.kwargs["pk"])
            .select_related("author")
            .order_by("-created")
        )

        context["is_following"] = is_following
        context["comments"] = comments
        context["comment_form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        comment = Comment(
            content=request.POST.get("content"),
            author=self.request.user,
            article=self.get_object(),
        )
        comment.save()
        return self.get(self, request, *args, **kwargs)


class ArticleCreateView(AuthorRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "world/articles/article_form.html"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()

        # save tags
        form.save_m2m()

        return super().form_valid(form)


class ArticleUpdateView(AuthorRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "world/articles/article_form.html"


class ArticleDeleteView(AuthorRequiredMixin, DeleteView):
    model = Article
    success_url = "/"


class ArticleFavoriteView(LoginRequiredMixin, UpdateView):
    fields = ["favorites"]
    http_method_names = ["post"]

    def get_queryset(self):
        return Article.objects.select_related("author").exclude(
            author=self.request.user
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.favorites.filter(id=request.user.id).exists():
            self.object.favorites.remove(request.user)
        else:
            self.object.favorites.add(request.user)

        return redirect(self.object.get_absolute_url())

world/apps/comments/views.py
from django.views.generic import DeleteView

from world.apps.core.mixins import AuthorRequiredMixin

from .models import Comment


class CommentDeleteView(AuthorRequiredMixin, DeleteView):
    model = Comment
    success_url = "/"

world/templates/world/articles/article_detail.html
{% extends "base.html" %}

{% block content %}
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1>{{ article.title }}</h1>
      <div class="article-meta">
        {% if article.author.image %}
          <img src="{{ article.author.image }}" width="32px" height="100%" alt="author image" />
        {% else %}
          <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" width="32px" height="100%" alt="author image" />
        {% endif %}
        <div class="info">
          <a href="{{ article.author.get_absolute_url }}" class="author">
            <span>{{ article.author.get_full_name }}</span>
          </a>
          <span class="date">{{ article.created|date:"F j, Y" }}</span>
        </div>
        {% if user == article.author %}
          <a href="{% url 'articles:edit' article.id %}" class="btn btn-outline-secondary btn-sm">
            <span>
              <i class="ion-edit"></i>
            </span>
            <span>Edit Article</span>
          </a>
          <form action="{% url 'articles:delete' article.id %}" method="post" style="display:inline-block" up-confirm="Really delete?">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">
              <span>
                <i class="ion-trash-a"></i>
              </span>
              <span>Delete Article</span>
            </button>
          </form>
        {% else %}
          {% include "world/accounts/partials/follow_btn.html" with followed=article.author %}
          {% include "world/articles/partials/favorite_btn.html" with is_favorite=article.is_favorite num_favorites=article.num_favorites %}
        {% endif %}
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <div>
          <p>{{ article.summary }}</p>
          {{ article.as_markdown|safe }}
        </div>
        {% with tags=article.tags.all %}
          {% if tags %}
            <ul class="tag-list">
              {% for tag in tags %}
                <li class="tag-default tag-pill tag-outline">
                  <a href="{% url 'articles:list' %}?tag={{ tag.name }}">{{ tag }}</a>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <hr />
    <div class="article-actions">
      <div class="article-meta">
        {% if article.author.image %}
          <img src="{{ article.author.image }}" width="32px" height="100%" alt="author image" />
        {% else %}
          <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" width="32px" height="100%" alt="author image" />
        {% endif %}
        <div class="info">
          <a href="{{ article.author.get_absolute_url }}" class="author">
            <span>{{ article.author.get_full_name }}</span>
          </a>
          <span class="date">{{ article.created|date:"F j, Y" }}</span>
        </div>
        {% if user == article.author %}
          <a href="{% url 'articles:edit' article.id %}" class="btn btn-outline-secondary btn-sm">
            <span>
              <i class="ion-edit"></i>
            </span>
            <span>Edit Article</span>
          </a>
          <form action="{% url 'articles:delete' article.id %}" method="post" style="display:inline-block" up-confirm="Really delete?">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">
              <span>
                <i class="ion-trash-a"></i>
              </span>
              <span>Delete Article</span>
            </button>
          </form>
        {% else %}
          {% include "world/accounts/partials/follow_btn.html" with followed=article.author %}
          {% include "world/articles/partials/favorite_btn.html" with is_favorite=article.is_favorite num_favorites=article.num_favorites %}
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        {% if user.is_authenticated %}
          <div>
            {% include "world/comments/comment_form.html" with form=comment_form %}
          </div>
        {% else %}
          <p style="text-align:center">
            <a href="{% url 'login' %}">Sign in</a>
            or
            <a href="{% url 'register' %}">sign up</a>
            to add comments on this article.
          </p>
        {% endif %}
        {% for comment in comments %}
          <div>
            {% include "world/comments/comment.html" %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

world/templates/world/articles/article_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="editor-page">
    <div class="container page">
      <div class="row">
        <div class="col-md-10 offset-md-1 col-xs-12">
          <form action="{{ request.path }}" method="post">
            {% csrf_token %}

            {% if form.errors %}
              <ul class="error-messages">
                {% for error in form.errors.values %}
                  {{ error.as_text }}
                {% endfor %}
              </ul>
            {% endif %}

            <fieldset class="form-group">
              {% render_field form.title class+="form-control form-control-lg" placeholder="Article Title" %}
            </fieldset>
            <fieldset class="form-group">
              {# see https://github.com/jazzband/django-widget-tweaks/issues/85 #}
              {{ form.summary|attr:"placeholder:What's this article about?"|add_class:"form-control" }}
            </fieldset>
            <fieldset class="form-group">
              {% render_field form.content class+="form-control" placeholder="Write your article (in markdown)" rows=8 %}
            </fieldset>
            <fieldset class="form-group">
              {% render_field form.tags class+="form-control" placeholder="Enter tags" autocomplete="off" %}
              <div class="tag-list" id="tags-list"></div>
            </fieldset>
            <fieldset>
              <button type="submit" class="btn btn-lg pull-xs-right btn-primary">
                <span>{{ article|yesno:"Save,Publish" }}</span>
                <span>Article</span>
              </button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

world/templates/world/articles/article_list.html
{% extends "base.html" %}

{% block content %}
<div class="home-page">
  {% if not user.is_authenticated %}
    <div class="banner">
      <div class="container">
        <h1 class="logo-font">conduit</h1>
        <p>A place to share your knowledge.</p>
      </div>
    </div>
  {% endif %}

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a href="{% url 'articles:list' %}" class="nav-link{% if not 'own' in request.get_full_path and not 'tag' in request.get_full_path %} active{% endif %}">
                <span>Global Articles</span>
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'articles:list' %}?own" class="nav-link{% if 'own' in request.get_full_path %} active{% endif %}">
                  <span>My Articles</span>
                </a>
              </li>
            {% endif %}
            {% if 'tag' in request.get_full_path %}
              <li class="nav-item">
                <a href="{{ request.get_full_path }}" class="nav-link{% if 'tag' in request.get_full_path %} active{% endif %}">
                  <span>
                    <i class="ion-pound"></i>
                  </span>
                  <span>{{ request.GET.tag }}</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
        {% for article in articles %}
          {% include "world/articles/partials/article.html" %}
        {% empty %}
          <div class="article-preview">No articles are here... yet.</div>
        {% endfor %}
      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>
          <div class="tag-list">
            {% for tag in tags %}
              <a href="{% url 'articles:list' %}?tag={{ tag.name }}" class="tag-pill tag-default">{{ tag }}</a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}